name: SAP Commerce Cloud Build and Test

on:
  workflow_dispatch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # You can choose a different runner if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This action checks out your repository code

      - name: Set up SAP Commerce environment
        run: |
          # export SAP_USERNAME=admin
          # export SAP_PASSWORD=nimda
          # ./install.sh -r b2c_acc -d <path_to_hybris_zip> initialize

      - name: Build SAP Commerce project
        run: |
           sudo su
           cd hybries/hybris/bin/platform
           ant clean all 

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: hybris/bin/custom/myextension/build/test-results  
 
          


   
